### PR TITLE
v1.12.0

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge-admin please rerender

**Comment by thewchan** [comment]
@conda-forge-admin please rerender

**Comment by thewchan** [comment]
@ivergara and @janjagusch any chance of merging this in for the newest version?

**Comment by janjagusch** [comment]
> @ivergara and @janjagusch any chance of merging this in for the newest version?

thanks for your contribution, @thewchan. i will first try to get the failing builds for the previous versions to work and then i will focus my attention on this pr.

**Comment by ivergara** [comment]
@thewchan Yes! Thank you for your help. Could you fix the conflict first? (probably rebase should be enough). Once there are no issues we can merge and have a new package available soon!

**Comment by thewchan** [comment]
@ivergara Done

**Review by janjagusch — CHANGES_REQUESTED** [review]
Let's merge this after I've released the other missing versions (will do so tomorrow).

**Comment by janjagusch** [comment]
@conda-forge-admin, please rerender

**Review by janjagusch — APPROVED** [review]
awesome job @thewchan!

**Pull request merged**
